# Generated by Django 4.0.3 on 2022-04-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_cliente_contacto_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
