# Generated by Django 4.0.3 on 2022-04-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_pais_estado_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='activo',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
