# Generated by Django 4.0.3 on 2022-04-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_alter_ciudad_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
