# Generated by Django 4.0.3 on 2022-04-21 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_alter_ciudad_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipper_Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('cp', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('c_nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('c_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('c_email', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Shipper'), (2, 'Delivery'), (3, 'Shipper/Delivery')], null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('register_by', models.IntegerField(blank=True, null=True)),
                ('cuidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.ciudad')),
            ],
        ),
    ]
