# Generated by Django 4.0.3 on 2022-04-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_shipper_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipper_delivery',
            name='c_email',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
