# Generated by Django 4.0.3 on 2022-05-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0012_orden_status_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='us_driver_two',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
