# Generated by Django 4.0.3 on 2022-07-14 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0014_personasistema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden_shipper_delivery',
            name='date_delivery',
        ),
        migrations.RemoveField(
            model_name='orden_shipper_delivery',
            name='date_shipp',
        ),
        migrations.RemoveField(
            model_name='orden_shipper_delivery',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='orden_shipper_delivery',
            name='delivery_notes',
        ),
        migrations.RemoveField(
            model_name='orden_shipper_delivery',
            name='shipper',
        ),
        migrations.RemoveField(
            model_name='orden_shipper_delivery',
            name='shipping_notes',
        ),
        migrations.CreateModel(
            name='ShipperDeliveryPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Shipper'), (2, 'Delivery')], null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('shipper_delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.shipper_delivery')),
            ],
        ),
    ]
