# Generated by Django 4.0.3 on 2022-07-15 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0015_remove_orden_shipper_delivery_date_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipperdeliverypoints',
            name='order_shipper_delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.orden_shipper_delivery'),
        ),
    ]
