# Generated by Django 4.0.3 on 2022-07-21 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0016_shipperdeliverypoints_order_shipper_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingLogOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('register_by', models.IntegerField(blank=True, null=True)),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.orden')),
                ('status_orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.status_orden')),
            ],
        ),
    ]
