# Generated by Django 4.0.3 on 2022-10-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0017_trackinglogorden'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='direccion_destino',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='direccion_origen',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
