# Generated by Django 4.0.3 on 2022-10-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0019_orden_cliente_cantidad_orden_cliente_factura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='proovedor_factura',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='proovedor_monto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='proveedor_pago_fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='proveedor_pago_monto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
