# Generated by Django 4.0.3 on 2022-11-03 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0020_orden_proovedor_factura_orden_proovedor_monto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='status_po',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='po_status', to='catalogo.status_orden'),
        ),
    ]
