# Generated by Django 4.0.3 on 2022-11-03 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0021_orden_status_po'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackinglogorden',
            name='status_po',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='po_status_tracking', to='catalogo.status_orden'),
        ),
    ]
