# Generated by Django 4.0.3 on 2022-11-24 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0022_trackinglogorden_status_po'),
    ]

    operations = [
        migrations.AddField(
            model_name='personasistema',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.cliente'),
        ),
    ]
