# Generated by Django 4.0.3 on 2023-04-18 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0024_orden_arrival_destination_orden_arrival_el_paso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='calle',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='cp',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='cuidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.ciudad'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='numero',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
