# Generated by Django 4.0.6 on 2023-05-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0028_camposdisponiblessistema_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='costo_adicional_cliente',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='costo_adicional_proveedor',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='costo_cliente',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='costo_proveedor',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
    ]
