# Generated by Django 4.0.6 on 2023-10-17 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0029_alter_orden_costo_adicional_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='cliente_iva_retenido',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='cliente_iva_trasladado',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='cliente_subtotal_monto',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
    ]
