# Generated by Django 4.0.6 on 2023-10-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0030_orden_cliente_iva_retenido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='cliente_tipo_cambio',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'USD'), (2, 'MXN')], null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='proveedor_tipo_cambio',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'USD'), (2, 'MXN')], null=True),
        ),
    ]
